import { StyleSheet } from "react-native";
// React Native numeric layout units map to dp; react-native-web maps them to CSS px.
export const fonts = {
  regular: "Hana2-Regular",
  medium: "Hana2-Medium",
  bold: "Hana2-Bold",
};
export const colors = {
  green: "#009B87",
  dark: "#202C30",
  text: "#202C30",
  muted: "#778286",
  line: "#E6E8E4",
  mint: "#EAF8F3",
  bg: "#F6F5F1",
  white: "#FFFFFF",
  canvas: "#E9EFEC",
  iconBg: "#F4F6F5",
  unchecked: "#AFB7B2",
  error: "#B94737",
  fontSpinner: "#008B78",
};
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#E9EFEC" },
  shell: {
    flex: 1,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: "#fff",
  },
  page: { paddingHorizontal: 22, paddingBottom: 28 },
  stickySearch: {
    backgroundColor: colors.white,
    paddingTop: 8,
    paddingBottom: 22,
  },
  row: { flexDirection: "row", alignItems: "center" },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  heading: {
    fontSize: 28,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: -0.8,
  },
  title: {
    fontSize: 19,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.5,
  },
  body: { fontSize: 16, color: colors.text, lineHeight: 23 },
  muted: { fontSize: 13, color: colors.muted, lineHeight: 19 },
  section: { marginTop: 26, marginBottom: 14 },
  recommendation: {
    backgroundColor: colors.mint,
    borderRadius: 22,
    padding: 20,
  },
  amount: {
    fontSize: 38,
    lineHeight: 46,
    color: colors.text,
    fontWeight: "700",
  },
  card: {
    borderRadius: 22,
    borderWidth: 2,
    borderColor: colors.unchecked,
    boxShadow: "0px 6px 16px rgba(32, 44, 48, 0.13)",
    backgroundColor: "#fff",
    marginBottom: 26,
  },
  cardImage: { height: 168, backgroundColor: "#F4F6F5" },
  cardBody: { padding: 20 },
  badge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 7,
    backgroundColor: colors.mint,
  },
  badgeText: { fontSize: 13, fontWeight: "600", color: colors.green },
  input: {
    backgroundColor: colors.white,
    fontFamily: fonts.regular,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 16,
    color: colors.text,
    minHeight: 56,
  },
  label: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 9,
  },
  field: { marginBottom: 22 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingVertical: 11,
    borderWidth: 1.5,
    borderColor: colors.unchecked,
    backgroundColor: "#fff",
  },
  chipActive: { backgroundColor: colors.mint, borderColor: colors.green },
  chipText: { color: colors.muted, fontSize: 13 },
  chipTextActive: { color: colors.green, fontWeight: "500" },
  button: {
    minHeight: 56,
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  buttonText: { color: colors.white, fontSize: 16, fontWeight: "500" },
  notice: {
    borderRadius: 14,
    backgroundColor: colors.bg,
    padding: 16,
    marginVertical: 16,
  },
  divider: { height: 1, backgroundColor: colors.line, marginVertical: 18 },
  modalRoot: { flex: 1, backgroundColor: "#E9EFEC" },
  modalShell: {
    flex: 1,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: "#fff",
  },
  header: {
    paddingHorizontal: 22,
    paddingVertical: 17,
    borderBottomWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footer: {
    padding: 22,
    borderTopWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#fff",
  },
  error: {
    color: "#B94737",
    backgroundColor: "#F6F5F1",
    borderRadius: 12,
    padding: 13,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 14,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 18,
    paddingVertical: 10,
  },
  detailLabel: { color: colors.muted, fontSize: 13 },
  detailValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: "600",
    textAlign: "right",
    flexShrink: 1,
  },
});
