import { StyleSheet } from "react-native";
export const colors = {
  green: "#009B83",
  dark: "#183D37",
  text: "#222E30",
  muted: "#7A878A",
  line: "#E9EEEE",
  mint: "#E9F8F3",
  bg: "#F7F9F9",
  purple: "#7471DE",
};
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#E9F0EE" },
  shell: {
    flex: 1,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
    backgroundColor: "#fff",
  },
  page: { paddingHorizontal: 24, paddingBottom: 28 },
  row: { flexDirection: "row", alignItems: "center" },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  heading: {
    fontSize: 24,
    fontWeight: "800",
    color: colors.text,
    letterSpacing: -0.8,
  },
  title: {
    fontSize: 19,
    fontWeight: "700",
    color: colors.text,
    letterSpacing: -0.5,
  },
  body: { fontSize: 14, color: colors.text, lineHeight: 23 },
  muted: { fontSize: 12, color: colors.muted, lineHeight: 19 },
  section: { marginTop: 26, marginBottom: 14 },
  card: {
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.line,
    overflow: "hidden",
    backgroundColor: "#fff",
    marginBottom: 18,
  },
  cardImage: { height: 168, backgroundColor: "#C9E3D9" },
  cardBody: { padding: 18 },
  badge: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 7,
    backgroundColor: colors.mint,
  },
  badgeText: { fontSize: 11, fontWeight: "600", color: colors.green },
  input: {
    backgroundColor: colors.bg,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    color: colors.text,
    minHeight: 50,
  },
  label: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 9,
  },
  field: { marginBottom: 22 },
  chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#fff",
  },
  chipActive: { backgroundColor: colors.dark, borderColor: colors.dark },
  chipText: { color: colors.muted, fontSize: 13 },
  chipTextActive: { color: "#fff", fontWeight: "600" },
  button: {
    minHeight: 54,
    borderRadius: 15,
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "700" },
  notice: {
    borderRadius: 14,
    backgroundColor: colors.mint,
    padding: 16,
    marginVertical: 16,
  },
  divider: { height: 1, backgroundColor: colors.line, marginVertical: 18 },
  modalRoot: { flex: 1, backgroundColor: "#E9F0EE" },
  modalShell: {
    flex: 1,
    width: "100%",
    maxWidth: 480,
    alignSelf: "center",
    backgroundColor: "#fff",
  },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 17,
    borderBottomWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footer: {
    padding: 20,
    borderTopWidth: 1,
    borderColor: colors.line,
    backgroundColor: "#fff",
  },
  error: {
    color: "#C5464D",
    backgroundColor: "#FFF1F1",
    borderRadius: 12,
    padding: 13,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 14,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 18,
    paddingVertical: 10,
  },
  detailLabel: { color: colors.muted, fontSize: 13 },
  detailValue: {
    color: colors.text,
    fontSize: 14,
    fontWeight: "600",
    textAlign: "right",
    flexShrink: 1,
  },
});
